apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite3
spec:
  replicas: 5
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: container5
          image: patillokesh/mywebsite3
          ports:
            - containerPort: 80
              protocol: TCP
